version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cusmbbrtq21c73b61ngg-a.singapore-postgres.render.com:5432/cada?sslmode=require
      SPRING_DATASOURCE_USERNAME: cada_user
      SPRING_DATASOURCE_PASSWORD: bn09FfAodFMFUEba1lqJjq8bvBlriwTn
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: cada_user
      POSTGRES_PASSWORD: bn09FfAodFMFUEba1lqJjq8bvBlriwTn
      POSTGRES_DB: cada
    ports:
      - "5432:5432"
